### ISSUE TITLE
Build Pre-Prototype

### ISSUE THREAD

**Issue by Mavro-Aspro** [Mavro-And-Aspro-Company/Mavro-And-Aspro-Company.github.io#8]

**Comment by Mavro-Aspro** [comment]
- [ ] Gather Google[ Managed Instance Grouping](https://cloud.google.com/compute/docs/instance-groups) Virtual Machine optimized performance to cost configurations for the different sources 

- [x] Use PAD documents and its requirements to build a per-prototype.

- [ ] Create a document containing performance report and list of tasks performed  in a checklist format [JBGE](https://agilemodeling.com/essays/barelyGoodEnough.html)

**Comment by Mavro-Aspro** [comment]
@rohitreddygade - Several instances were created which caused increase in cost of computation and other resources..!! Please use resources careful.

**Comment by rohitreddygade** [comment]
Creations and observations of Virtual Private Cloud, its Testing and Monitoring phase report[ VPC doc](https://app.box.com/s/2uj0mdulanl8i3akormsw8otss88o8j5) and [ K8 observations  ](https://app.box.com/s/t31tcb2yb877zw8cn00jqen1x3cvllm3)

**Comment by Mavro-Aspro** [comment]
Hi @rohitreddygade . Well Congratulations on completing the first pre-pototype report. 

I went a head and created the second Epic for the prototype build. named Pre-Prototype 2. Rather than doing it in last minuter rush, hopefully it will be done it even period of time intervals and this epic is going will contain small period of time frame.
